### PR TITLE
Variation Documentation Updates for 104

### PR DESCRIPTION
**Pull request by aparton**

### CODE REVIEW

**Comment by ens-st3** [comment]
Just 104, or also master ?

**Comment by aparton** [comment]
Yes, it's also required on master I'm afraid. Should I change this PR onto postreleasefix/104, or shall I create a second PR just for master?

**Comment by ens-st3** [comment]
Can you submit it against postreleasefix/104 (keeps the git tree cleaner) ?

**Comment by aparton** [comment]
Done, #453

**Pull request closed without merging**
