### PR TITLE
Change sidebar position to absolute

### PR DESCRIPTION
**Pull request by msmanoj**
Description
- Changed the position of the sidebar from fixed to absolute and removed the onScroll handler

Related JIRA:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5593

Sandbox URL: (Minimise the screen size to test)
http://ves-hx2-75.ebi.ac.uk:42228/Multi/Search/Results?q=BRCA2;site=ensembl_all;page=2;perpage=10

### CODE REVIEW

**Comment by ens-ap5** [comment]
I'm not clear on what I'm meant to be testing - I can't see any difference.

**Comment by msmanoj** [comment]
> I'm not clear on what I'm meant to be testing - I can't see any difference.

@ens-ap5 - please notice the behaviour of the sidebar as I scroll down on small screen. It seems to be jumping randomly.
Solr search

**Review by ens-ap5 — APPROVED** [review]
Is that in Chrome? I don't really see any difference in Firefox - the live site doesn't show that jumping, at least not for me. I'll trust that what you've done works, though!

**Comment by msmanoj** [comment]
> Is that in Chrome? I don't really see any difference in Firefox - the live site doesn't show that jumping, at least not for me. I'll trust that what you've done works, though!



> Is that in Chrome? I don't really see any difference in Firefox - the live site doesn't show that jumping, at least not for me. I'll trust that what you've done works, though!

Could you try it by reducing the window size?

**Comment by ens-ap5** [comment]
I did - I made my window about the same size as in your animation.

**Comment by msmanoj** [comment]
> I did - I made my window about the same size as in your animation.

Not quite sure why it's not doing it for you but this issue is something Andrey noticed during a zoom meet.

**Review by ens-st3 — APPROVED** [review]
Sorry Manoj, I thought I'd replied. I can't replicate this either, but happy to approve it

**Pull request merged**
