### PR TITLE
Update about us description.

### PR DESCRIPTION
**Pull request by mehrnazcharkhchi**

### CODE REVIEW

**Comment by ens-st3** [comment]
Can you link to the JIRA in the PR description,  and vice versa ?

**Comment by ens-st3** [comment]
This will need to go onto master too (using mpush)

**Comment by mehrnazcharkhchi** [comment]
> This will need to go onto master too (using mpush)

Here is the jira ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5883
I will apply this into both branches then.

**Comment by msmanoj** [comment]
Hi @mehrnazcharkhchi, can this PR be merged?

**Comment by msmanoj** [comment]
Superseded by https://github.com/Ensembl/public-plugins/pull/369

**Pull request closed without merging**
