### PR TITLE
Add 3D viewer to VEP results and it includes other minor display upda…

### PR DESCRIPTION
**Pull request by ens-lgil**
…tes and improvements for the others 3D viewer pages (Transcript and Variation).

- Add buttons, module and configuration for the new 3D viewer page from the VEP results
- Some changes in the 3D viewer display
- Some changes in the 3D viewer JS code (to integrate the VEP results and also some general optimisation).

### Example of 3D viewer button in the VEP results table
Column `Domains`:
http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Tools/VEP/Results?tl=HHzqSVdPXIKhTiMh-526

### Example of 3D viewer from VEP results:
- [rs334](http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Tools/VEP/PDB?cons=missense_variant;db=core;g=ENSG00000244734;pos=7;r=11:5225464-5229395;t=ENST00000335295;tl=HHzqSVdPXIKhTiMh-526;var=rs334)
- [stop_gained](http://ves-hx2-76.ebi.ac.uk:5060/Homo_sapiens/Tools/VEP/PDB?cons=stop_gained;db=core;g=ENSG00000135744;pos=400;r=1:230702523-230714122;t=ENST00000366667;tl=BVlsqvDkzJHrWxsT-527;var=1_230704264_C/A)

### CODE REVIEW

**Comment by ens-ma7** [comment]
@ens-lgil these changes are quite big, i think its better we have a code review to discuss this if thats ok with you

**Comment by ens-lgil** [comment]
@ens-ma7 yes sure!

**Comment by ens-ma7** [comment]
what about next wednesday at 11?

**Comment by ens-ma7** [comment]
Had code review and suggested a few improvement which @ens-lgil is going to do and then create another pull request. @ens-lgil please close this PR if its not needed.

**Comment by ens-lgil** [comment]
Will send a new PR

**Pull request closed without merging**
