### PR TITLE
Update categories for VEP plugins (e112)

### PR DESCRIPTION
**Pull request by nuno-agostinho**
[ENSVAR-6173](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6173): Move OpenTargets to the `Variant and Allele Frequency` section
[ENSVAR-6096](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6096): Add plugins to new section `Gene tolerance to change`

Related with https://github.com/Ensembl/VEP_plugins/pull/693

## Testing

Check changes in my sandbox:
- [Web VEP input form](http://wp-np2-11.ebi.ac.uk:6070/Multi/Tools/VEP?db=core)
- [Web VEP input form docs](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/input.html)

### CODE REVIEW

**Review by jamie-m-a — APPROVED** [review]
Looks great, thanks for rearranging these Nuno

**Comment by jyothishnt** [comment]
@nuno-agostinho Please could you resolve the conflicts? thanks

**Comment by nuno-agostinho** [comment]
Hey @jyothishnt, fixed!

**Comment by nuno-agostinho** [comment]
Hey @jyothishnt, fixed!

**Pull request merged**
