### PR TITLE
Apply changes in 1000g FTP file names.

### PR DESCRIPTION
**Pull request by Mehrnaz-Charkhchi**

### CODE REVIEW

**Review by ens-st3 — APPROVED** [review]

**Comment by ens-ma7** [comment]
@Mehrnaz-Charkhchi i don't think that's the only place that needs changing. The code you changed is just a text description, its not the actual piece of code that does the fetching of the file.  I cant remember where it is exactly but there is also a request in the JS file and probably something in the SiteDefs.pm as well.
Let me know if you cant find it, i can help you with it.

**Comment by ens-ma7** [comment]
@Mehrnaz-Charkhchi sorry ignore my comment above, i didnt see your other PR in public-plugins.

**Comment by Mehrnaz-Charkhchi** [comment]
> @Mehrnaz-Charkhchi i don't think that's the only place that needs changing. The code you changed is just a text description, its not the actual piece of code that does the fetching of the file. I cant remember where it is exactly but there is also a request in the JS file and probably something in the SiteDefs.pm as well.
> Let me know if you cant find it, i can help you with it.

@ens-ma7 Done!

**Comment by ens-ma7** [comment]
@Mehrnaz-Charkhchi  The PR is against release/103 branch. You probably want to do the PR against postreleasefix/103 branch but first you need to create your branch from the postreleasefix/103 branch.

**Comment by Mehrnaz-Charkhchi** [comment]
> @Mehrnaz-Charkhchi The PR is against release/103 branch. You probably want to do the PR against postreleasefix/103 branch but first you need to create your branch from the postreleasefix/103 branch.

@ens-ma7 Source and base branch is updated to postreleasefix/103.

**Review by ens-ma7 — APPROVED** [review]

**Comment by ens-ma7** [comment]
@Mehrnaz-Charkhchi i have approved the change but we still need to fix the issue with the live tools with the 1000Genomes API being down (I understand we are waiting to hear from susan). These changes are just text change, you can still push these changes live but the tools wont be fixed by these.

**Comment by Mehrnaz-Charkhchi** [comment]
@ens-ma7 True, I added another commit  with file name updates to help users work with sample files.

**Review by ens-ma7 — APPROVED** [review]

**Pull request merged**
