### PR TITLE
Fix Windows new line chars

### PR DESCRIPTION
**Pull request by tuanebi**
There are RT tickets (417267, 416182) reporting an issue with PostGap. It turns out the users use Windows-style input file which has CRLF (\r\n) as new line chars. Our code only considers the Unix-style input (\n for new lines). 

This part here fails with Windows-style input because we expect `p-value` but Perl's chomp method give us `p-value\r`
https://github.com/Ensembl/public-plugins/blob/release/100/tools_hive/modules/EnsEMBL/Web/RunnableDB/Postgap.pm#L217-L221

### CODE REVIEW

**Comment by ens-ma7** [comment]
@tuanebi have you checked if this works with linux style file where there is no \R or maybe you need your regex to not be case sensitive?

**Comment by ens-ma7** [comment]
also @tuanebi the PR needs to be against postreleasefix/100 branch

**Comment by tuanebi** [comment]
@ens-ma7 \R will match \r | \n | \r\n and also anything considered a linebreak sequence by Unicode, according to the doc here
https://perldoc.perl.org/perlrebackslash.html#Misc

I tested both Windows and Linux input format. 
My sandbox http://ves-hx2-75.ebi.ac.uk:9580/Homo_sapiens/Tools/Postgap so it would be best if you can test some inputs.

I'll create another PR to postreleasefix/100

**Comment by tuanebi** [comment]
@ens-ma7 I changed the base branch of this PR from release/100 to postreleasefix/100

**Comment by tuanebi** [comment]
mpush DONE: Successfully updated both branches with following commit(s):
e8e6985d9 Fix removing new line chars

**Pull request closed without merging**
