### PR TITLE
[ON HOLD] Add source param to the gxa request url

### PR DESCRIPTION
**Pull request by msmanoj**
Description:
This PR fixes the broken Expression Atlas widget for Fruit Fly (also other species?). The issue was with the missing 'source' param in the request that gets sent to gxa

Sandbox URLs:
Works fine for Humans and Fruit fly:
http://wp-np2-1d.ebi.ac.uk:42229/Homo_sapiens/Gene/ExpressionAtlas?g=ENSG00000139618;r=13:32315086-32400268

http://wp-np2-1d.ebi.ac.uk:42229/Drosophila_melanogaster/Gene/ExpressionAtlas?db=core;g=FBgn0004513;r=3L:6240500-6245746;t=FBtr0077011

Still breaks for Zebrafish:
http://wp-np2-1d.ebi.ac.uk:42229/Danio_rerio/Gene/ExpressionAtlas?g=ENSDARG00000024771;r=18:5213338-5227420;t=ENSDART00000033574

Related JIRA ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4932

### CODE REVIEW

**Comment by ens-st3** [comment]
I'm afraid this breaks human:
http://ves-hx2-76.ebi.ac.uk:42228/Homo_sapiens/Gene/ExpressionAtlas?g=ENSG00000139618;r=13:32315086-32400266

**Comment by ens-ap5** [comment]
Since this has been hanging around for over six months, would it be acceptable to add an if block so that we pass different parameters when the species is human? Hacky, I know, but it seems a shame to omit GXA for species where this info is available.

**Comment by ens-ma7** [comment]
Looking at the attached JIRA, it seems they should have an API by now to check this. I remembered doing another check (i think it was the widget availability), probably good to check with them again if they have the API, if not they might be able to help with another link to check.

**Comment by msmanoj** [comment]
Closing this PR as we do not have a clear solution or a workaround for this yet. We can create a different PR when we have a solution instead of keeping this one.

**Pull request closed without merging**
