### PR TITLE
Remove the edit fav genome icon

### PR DESCRIPTION
**Pull request by msmanoj**
I am currently overriding the entires `_get_dom_tree` method to remove the edit icon. Please let me know if it can be done in a better way.

Related JIRAs:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5821
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5831

Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42228/index.html

### CODE REVIEW

**Comment by ens-ap5** [comment]
A more robust approach would be to turn this line: https://github.com/Ensembl/ensembl-webcode/blob/release/100/modules/EnsEMBL/Web/Document/HTML/GenomeList.pm#L92

into a method call, then override that method in this module, to return an empty string.

**Comment by msmanoj** [comment]
Thanks @ens-ap5. I have made the changes as you have suggested above.

The ensembl-webcode changes are made in the following commit:
https://github.com/Ensembl/ensembl-webcode/commit/c18c661b020b91fb3c9b6d2969da42bad6672650

**Comment by msmanoj** [comment]
@ens-ap5 a similar change was needed for the other ticket https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5831 as well so I have pushed it to this PR to keep it simple. 

Related commit on ensembl-webcode:
https://github.com/Ensembl/ensembl-webcode/commit/7f925dc1f7655cd9b256daeb8c3e484cf6207a3b

**Comment by ens-ap5** [comment]
It mostly looks good, but I'm unsure of the point of this HTML:

<h3 class="space-above"></h3>

**Comment by msmanoj** [comment]
> It mostly looks good, but I'm unsure of the point of this HTML:
> 
> `<h3 class="space-above"></h3>`

It looks like it's adding the following `margin-top: 2em;`. It was already there so I just left it as it is.

**Pull request merged**
