### PR TITLE
Rat mRatBN7.2 annotation documentation

### PR DESCRIPTION
**Pull request by thibauthourlier**

### CODE REVIEW

**Comment by ens-st3** [comment]
Can you resubmit this against postreleasefix/105 ?

**Comment by thibauthourlier** [comment]
Sorry, Steve's request got buried in other emails, https://github.com/Ensembl/public-plugins/pull/494

**Review by ens-ap5 — CHANGES_REQUESTED** [review]
There are changes in here from other people's commits (the covid ones) - could you update this PR, please?

**Comment by imransl** [comment]
@ens-ap5 @thibauthourlier Can we close this PR as #494 seems to be the better one?

**Comment by thibauthourlier** [comment]
I'm happy for it to be closed

**Comment by imransl** [comment]
Closing this PR in favour of #494

**Pull request closed without merging**
