### PR TITLE
draft compara text

### PR DESCRIPTION
**Pull request by nds**

### CODE REVIEW

**Comment by ens-ds23** [comment]
Hi @nds . This is against 104. Which release is it for? 105 or 106 or is this some advanced rapid/covid thing I don't understand?

**Comment by ens-st3** [comment]
It needs to go to 104, 105 and master. The PR should really be against postreleasefix/104 with a cherry pick to 105

**Comment by ens-ds23** [comment]
I'll put it onto postreleasefix/104 and merge it onto master and release/104 and then cherry pick it separately onto release/105. I assume there's no efforts needed to update 104 instances at this stage @ens-st3 ?

**Comment by ens-st3** [comment]
It's for the covid-19 site

**Comment by ens-ds23** [comment]
Bother I merged onto release/104 not postreleasefix/104. Not my day. Time for some tinkering.

**Comment by ens-ds23** [comment]
Ok. Now directly on postreleasefix/104 and that pushed to master and release/104. And also on release/105 (but not postreleasefix/105) via cherry-pick.

**Pull request merged**
