### PR TITLE
Remove postgap from tools setup

### PR DESCRIPTION
**Pull request by jgtate**
## Description

The Post-GWAS tool is being [retired in 108](https://www.ensembl.info/2022/07/28/retiring-the-post-gwas-tool/). This PR removes the configuration related to the tool.

See the [complementary PR](https://github.com/Ensembl/ensembl-webcode/pull/922) in [ensembl-webcode](https://github.com/Ensembl/ensembl-webcode) that removes the Post-GWAS line in the tools table, and in [ebi-plugins](https://github.com/Ensembl/ebi-plugins/pull/133) that removes more mentions in config.

## Views affected

None specifically, but see the tools index page in the [sandbox](http://wp-np2-1f.ebi.ac.uk:8800/info/docs/tools/index.html).

## Possible complications

None

## Merge conflicts

None

## Related JIRA Issues (EBI developers only)

This PR fulfills the first part of [ENSWEB-6588](https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-6588).

### CODE REVIEW

**Comment by ens-ma7** [comment]
@jgtate  Not sure if thats on your todo list already but there are also changes in ebi-plugins:
https://github.com/Ensembl/ebi-plugins/blob/552733dba159a3d98b19be82fa7276ef8ded650f/grch37/conf/SiteDefs.pm#L97

Its harmless since it is disabling the postgap tool but probably will be good to cleanup the code just in case we ask ourselves what is this line doing here in the future. 

might probably be good to do a grep in the ebi-plugins of this variable (ENSEMBL_PG_ENABLED).

Will be good to check the ensembl-genomes repo as well.

**Review by ens-ma7 — CHANGES_REQUESTED** [review]
Changes that can be done post release:
https://github.com/Ensembl/public-plugins/blob/d31074643e2a80a300fda184793591c79f10503c/tools/conf/SiteDefs.pm#L120-L123

**Review by ens-ma7 — APPROVED** [review]

**Comment by jgtate** [comment]
Added another PR to remove config mentioned here in [ebi-plugins](https://github.com/Ensembl/ebi-plugins/pull/133).

**Comment by jgtate** [comment]
> Will be good to check the ensembl-genomes repo as well.

Can't see any references to postgap in any of the EnsemblGenomes repos but if there's somewhere specific I should look I'm happy to add further PRs.

**Review by ens-ap5 — COMMENTED** [review]
Code-wise this looks fine. Have we confirmed that it's OK for people's old postgap jobs to just go away? Or is that dealt with by the blog post?

**Pull request merged**
