### PR TITLE
Add AlphaMissense plugin to web VEP (e111)

### PR DESCRIPTION
**Pull request by nuno-agostinho**
[ENSVAR-6261](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-6261)

## Testing

Please test in my sandbox:
- [Web VEP](http://wp-np2-11.ebi.ac.uk:6070/Tools/VEP)
- [Docs update](http://wp-np2-11.ebi.ac.uk:6070/info/docs/tools/vep/online/input.html)

### CODE REVIEW

**Comment by sarahhunt** [comment]
Thanks @nuno-agostinho - that was quick! It looks good but needs a couple of tweeks.

On the results page, we don't want to show the file location in the mouse over help. Can you switch these descriptions to-

- score - "A continuous score between 0 and 1 which can be interpreted as the predicted probability of the variant being pathogenic."

- classification - "The thresholds are: 'Likely benign' if score < 0.34; 'Likely pathogenic' if score > 0.564; 'ambiguous' otherwise. See https://doi.org/10.1126/science.adg7492 for details"

Thanks!

**Comment by nuno-agostinho** [comment]
Updated header description at the plugin level: https://github.com/Ensembl/VEP_plugins/pull/705

**Comment by jamie-m-a** [comment]
Hi @nuno-agostinho I think there's still some text missing in the hover text vs. what @sarahhunt  was asking for?

**Review by jamie-m-a — APPROVED** [review]
Looks good thanks for the changes Nuno!

**Comment by sarahhunt** [comment]
Thanks @nuno-agostinho ! @jonk-ebi - this one is ready to go.

**Comment by jyothishnt** [comment]
Hi, this branch was branched out of main and was requested to merge into postreleasefix/111. I merged it by mistake. I have cleaned the branches now and it is back in its previous state. Please could you create another PR branched out of postreleasefix/111

**Pull request merged**
