### PR TITLE
Updated ini files for primates example regions

### PR DESCRIPTION
**Pull request by leannehaggerty**
I've added location info for the primates, please let me know if there are any problems :)

### CODE REVIEW

**Comment by ens-ap5** [comment]
Hi Leanne, did you mean to remove the variation examples and VEP parameters? The former are needed on the species homepages and latter are the examples used by the tools interface

**Comment by leannehaggerty** [comment]
Sorry Anne, I did not, I was copying and pasting my generated text so I obviously just overwrote text. I’ll pop it back in and update the PR

Thanks
Leanne

**Comment by ens-ap5** [comment]
No worries - I'll have another look when you're done

**Comment by leannehaggerty** [comment]
Hi Anne, 

All the info should be back now, let me know if I've missed anything

Thanks
Leanne

**Pull request merged**
