### PR TITLE
Configure updated vertebrates for e103

### PR DESCRIPTION
**Pull request by azangru**
Jira ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-989

Looks like our updated assemblies are ahead of UCSC. I'm removing the links to the older assemblies at UCSC.

**Reference** (from the report of updated species):

```json
   "vertebrates" : {
      "new_genomes" : {},
      "removed_genomes" : {},
      "renamed_genomes" : {},
      "updated_assemblies" : {
         "mus_musculus" : {
            "old_assembly" : "GRCm38",
            "name" : "mus_musculus",
            "assembly" : "GRCm39",
            "species_id" : 1,
            "has_variation" : 1,
            "has_microarray" : 1,
            "database" : "mus_musculus_core_103_39",
            "strain" : "reference (CL57BL6)"
         },
         "ailuropoda_melanoleuca" : {
            "old_assembly" : "ailMel1",
            "name" : "ailuropoda_melanoleuca",
            "assembly" : "ASM200744v2",
            "species_id" : 1,
            "has_variation" : 0,
            "has_microarray" : 0,
            "database" : "ailuropoda_melanoleuca_core_103_2",
            "strain" : null
         },
         "gadus_morhua" : {
            "has_microarray" : 0,
            "strain" : null,
            "database" : "gadus_morhua_core_103_3",
            "has_variation" : 0,
            "species_id" : 1,
            "assembly" : "gadMor3.0",
            "name" : "gadus_morhua",
            "old_assembly" : "gadMor1"
         },
         "macaca_fascicularis" : {
            "species_id" : 1,
            "has_variation" : 0,
            "database" : "macaca_fascicularis_core_103_6",
            "strain" : null,
            "has_microarray" : 1,
            "old_assembly" : "Macaca_fascicularis_5.0",
            "name" : "macaca_fascicularis",
            "assembly" : "Macaca_fascicularis_6.0"
         },
         "drosophila_melanogaster" : {
            "has_variation" : 0,
            "species_id" : 1,
            "strain" : null,
            "database" : "drosophila_melanogaster_core_103_9",
            "has_microarray" : 1,
            "old_assembly" : "BDGP6.28",
            "assembly" : "BDGP6.32",
            "name" : "drosophila_melanogaster"
         },
         "anabas_testudineus" : {
            "old_assembly" : "fAnaTes1.1",
            "name" : "anabas_testudineus",
            "assembly" : "fAnaTes1.2",
            "species_id" : 1,
            "has_variation" : 0,
            "database" : "anabas_testudineus_core_103_12",
            "strain" : null,
            "has_microarray" : 0
         },
         "mastacembelus_armatus" : {
            "old_assembly" : "fMasArm1.1",
            "assembly" : "fMasArm1.2",
            "name" : "mastacembelus_armatus",
            "has_variation" : 0,
            "species_id" : 1,
            "has_microarray" : 0,
            "strain" : null,
            "database" : "mastacembelus_armatus_core_103_12"
         }
      },
```

### CODE REVIEW

**Review by ens-ap5 — CHANGES_REQUESTED** [review]
If the older assemblies are present on UCSC, we should add the assembly mapping, similar to that seen in, e.g. mouse: https://github.com/Ensembl/public-plugins/blob/release/102/ensembl/conf/ini-files/mus_musculus.ini#L20

**Comment by ens-st3** [comment]
> If the older assemblies are present on UCSC, we should add the assembly mapping, similar to that seen in, e.g. mouse: https://github.com/Ensembl/public-plugins/blob/release/102/ensembl/conf/ini-files/mus_musculus.ini#L20

What's that line used for @ens-ap5 ?

**Comment by ens-ap5** [comment]
@ens-st3 When someone tries to attach a trackhub with an assembly name that doesn't match either the current Ensembl assembly name for that species or the UCSC equivalent, we check the other mappings and if we find a match, advise the user that they can use one of our archives instead. I can't remember if we suggest a specific archive or if it's just a courtesy message.

**Comment by azangru** [comment]
Assembly names for the panda, the cod, and the macaque are the same at Ensembl and UCSC. I've updated the mapping for the new mouse assembly.

I'll need to update files for model organisms whose assemblies got updated. E.g. drosophila — I only updated it in eg-web-metazoa.

**Comment by azangru** [comment]
Turns out, I already updated the drosophila assembly in the ini file a month ago, and completely forgot about this.

@ens-ap5 Would you say this PR is good to merge into species-update?

**Comment by ens-ap5** [comment]
OK, I'm happy with it!

**Pull request merged**
