### PR TITLE
Peak calling report table pagination

### PR DESCRIPTION
**Pull request by msmanoj**
Enabled the pagination for the Regulatory Build Statistics tables

Related JIRA ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5391

Sandbox URL:
http://ves-hx2-76.ebi.ac.uk:42229/info/genome/funcgen/peak_calling_report.html

### CODE REVIEW

**Comment by jyothishnt** [comment]
Thanks Manoj, Looks good.

**Comment by jyothishnt** [comment]
Have same issues on other new reg stat pages too. Please could you fix them as well? Thanks

**Comment by msmanoj** [comment]
> Have same issues on other new reg stat pages too. Please could you fix them as well? Thanks

That's all done 👍

**Comment by jyothishnt** [comment]
Missed the table in segmentation doc. :-)

**Comment by msmanoj** [comment]
> Missed the table in segmentation doc. :-)

That's done now 👍

**Comment by jyothishnt** [comment]
Looks good @msmanoj . Please make sure css works on staging after merge.

**Comment by msmanoj** [comment]
> Please make sure css works on staging after merge.

I have checked on my other sandbox and the css loads fine.

**Pull request merged**
