### PR TITLE
update reg. stats for r109

### PR DESCRIPTION
**Pull request by pblins**
Release 109 regulatory feature stats update.

- Jira ticket: [ENSREGULATION-1619](https://www.ebi.ac.uk/panda/jira/browse/ENSREGULATION-1619)
- Sandbox: [stats page](http://wp-np2-25.ebi.ac.uk:6020/info/genome/funcgen/statistics/annotation.html)

### CODE REVIEW

**Comment by azangru** [comment]
We are seeing these javascript errors in the console (present on the live site as well). @jyothishnt and @veidenberg will take a look at this.

image

**Comment by veidenberg** [comment]
There first error fails a function that tries to load nonexistent jquery plugin to add interactivity to a table (not sure if worth to fix). Still looking in to the second error.

**Comment by veidenberg** [comment]
There are 3 different Javascript errors that can be fixed in `annotation.html` file as follows (tested in my sandox):
* On [line 40](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L40), jQuery is used before it is available (the script file is loaded later in the html file). Replace the line with `window.onload = function () { ... };`. Note that although it fixes the error, the intended action (using a plugin to add interactivity to the summary table) doesn't seem to take effect. This needs further investigation.
*  [Line 607](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L607) tries to load a missing `utils.js` file. Judging from the [source code](https://github.com/sgratzl/chartjs-chart-boxplot/blob/main/samples/utils.js), it seems that the script is now used with a different filename (`RegulationChartUtils` in [line 13](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L13)), but the old script tag has been left in the html. Please delete the line 607.
* [Line 311](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L311) tries to select a non-existent DOM element and later to draw a venn diagram into it. It seems that in the [108 update PR](https://github.com/Ensembl/public-plugins/pull/608), the html elements for the diagram (together with "Stable ID" section) were removed, but the associated javascript (and chart data) were left in place. Please remove it (lines [272](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L272) - [350](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L350)) to finish the cleanup.

Please add the suggested changes to this PR and see if it fixes the errors in your sandbox. Thanks!

**Review by veidenberg — CHANGES_REQUESTED** [review]
There are 3 different Javascript errors that can be fixed in `annotation.html` file as follows (tested in my sandox):
* On [line 40](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L40), jQuery is used before it is available (the script file is loaded later in the html file). Replace the line with `window.onload = function () { ... };`. Note that although it fixes the error, the intended action (using a plugin to add interactivity to the summary table) doesn't seem to take effect. This needs further investigation.
*  [Line 607](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L607) tries to load a missing `utils.js` file. Judging from the [source code](https://github.com/sgratzl/chartjs-chart-boxplot/blob/main/samples/utils.js), it seems that the script is now used with a different filename (`RegulationChartUtils` in [line 13](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L13)), but the old script tag has been left in the html. Please delete the line 607.
* [Line 311](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L311) tries to select a non-existent DOM element and later to draw a venn diagram into it. It seems that in the [108 update PR](https://github.com/Ensembl/public-plugins/pull/608), the html elements for the diagram (together with "Stable ID" section) were removed, but the associated javascript (and chart data) were left in place. Please remove it (lines [272](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L272) - [350](https://github.com/Ensembl/public-plugins/blob/d4ab3886e487f916e668c4f5b4edd8af51f6ed0f/ensembl/htdocs/info/genome/funcgen/statistics/annotation.html#L350)) to finish the cleanup.

Please add the suggested changes to this PR and see if it fixes the errors in your sandbox. Thanks!

**Review by veidenberg — APPROVED** [review]
Looks good, no Javascript errors. 
The line `$('#overview').DataTable();` still doesn't seem to have any effect, but that's something for you to investigate (either to fix or remove in next update).

**Pull request merged**
