### PR TITLE
use release version

### PR DESCRIPTION
**Pull request by at7**
I updated the path to use the release version. This will be important to get the correct data when checking archive sites.

### CODE REVIEW

**Comment by ens-ma7** [comment]
@at7 but that means for each release we will have to update the path?

**Comment by at7** [comment]
The data is not static and compara includes new species every release. If we keep updating the release version and the new new name of the alignment directory (from 75_mammals.gerp_conservation_score in release-95 to 88_mammals.gerp_conservation_score in release-96) we will be backwards compatible for archive sites. They might not always increase but I think this way we are safe?

**Comment by ens-ap5** [comment]
Given that the first part of the URL is identical in each species ('ftp://ftp.ensembl.org/pub/current_compara/conservation_scores/'), it would make sense to generate it in the code that consumes the JSON, instead of having the full path hard-coded. Then we wouldn't need to update it every release, just when the number of mammals in the GERP alignment changes.

**Comment by at7** [comment]
I like that. Shall we create a ticket for this for next time or is there time do it for 96? I can adjust the paths accordingly in the config files.

**Comment by ens-ap5** [comment]
It should be a simple change. Put in a ticket now and I'll pick it up, like we did for the vervet variation link.

**Comment by at7** [comment]
Here is the ticket: https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-4943
Thank you

**Comment by ens-ma7** [comment]
Thanks @ens-ap5, i was going to suggest the same thing, you are too quick in responding, i was confused, i thought i was replying on an all PR.

I will leave this PR open until you have your changes in @ens-ap5 , feel free to close it once you are happy.

**Comment by ens-ap5** [comment]
Sorry, I thought I'd chime in since I saw an obvious solution :)

**Comment by ens-ma7** [comment]
No problem at all, its just that within 5 minutes there was like 4 comments on the PR :) anyway its all yours now :)

**Comment by at7** [comment]
Is this what you had in mind? If yes, I will update the other species as well.

**Comment by ens-ap5** [comment]
Yes, that's perfect!

**Pull request merged**
