### PR TITLE
Update gnomad version for 106

### PR DESCRIPTION
**Pull request by dglemos**
Release 106

### CODE REVIEW

**Review by jamie-m-a — APPROVED** [review]

**Comment by jamie-m-a** [comment]
Looks good to me

**Comment by dglemos** [comment]
@helensch I wasn't sure I needed to update populations.html now. I was confused because of this PR: https://github.com/Ensembl/public-plugins/pull/454 but I can see that it was done after documentation PR.
I can remove the docs update from this PR.

**Comment by dglemos** [comment]
Documentation update was removed from PR. It will be done as part of web variation documentation.

**Comment by jgtate** [comment]
Are you happy with @dglemos 's latest update, @helensch ? If it's okay could you approve the PR and I'll merge it as soon as I can.

**Review by helensch — APPROVED** [review]

**Comment by helensch** [comment]
@dglemos and @jgtate yes the changes are good and I have approved the PR

**Pull request merged**
