### PR TITLE
Added a link to the CAFE publication

### PR DESCRIPTION
**Pull request by muffato**
Request from Paul K.

See it working at http://enssand-01.internal.sanger.ac.uk:9073/Homo_sapiens/Gene/SpeciesTree?db=core;g=ENSG00000139618;gtr=order;r=13:32315474-32400266

### CODE REVIEW

**Comment by ens-ma7** [comment]
Hi Matthieu
Do you want this to go on the branch release/85 only ?

if you want it to go both on master and release branch, can you please do the pull request on postreleasefix/85

Ridwan

**Comment by muffato** [comment]
There was no postreleasefix branch when I checked: only master and release/85 and they were pointing at the same commit

**Comment by ens-ma7** [comment]
Ok sorry thought it was the webcode, i am going to merge it now.

**Comment by muffato** [comment]
super, thank you !

**Comment by ens-ma7** [comment]
The changes have been pushed to the live server. Can you please check your changes on the live site to make sure nothing is broken. let me know if there is any problem.

**Comment by muffato** [comment]
Yes, I checked and it worked. Thank you !

**Pull request merged**
