### PR TITLE
Update urls for 1000 genomes ftp site

### PR DESCRIPTION
**Pull request by azangru**
Update ftp host name for 1000 ftp server.

Also, hack our way on the client where we talk with the search server at https://www.internationalgenome.org. The server has to receive ftp url as a parameter, returns empty response if we change the ftp url to the new one, and  is not going to be reconfigured to correctly handle the new one 😞 

**Jira:** ENSWEB-5524

**Sandbox:** http://ves-hx2-76.ebi.ac.uk:8410/info/docs/tools/index.html

~Related PR in ebi-plugins: https://github.com/Ensembl/ebi-plugins/pull/36~

### CODE REVIEW

**Comment by ens-ma7** [comment]
Codes change are ok. Just a few clarification:
1) URL hasn't been updated in the documentation, i noticed this was asked in the jira ticket but couldn't find any reply, i guess the decision was to keep the old URL in the documentation?
2) The hack makes sense but clarification on this, will we revert back to the old URL after the DC migration because the comment says hack for DC migration? My understanding is that it will stay like this, not sure. If it is a permanent change, we need to make sure the old 1000G ftp URL is always kept working or else their API will fail.

**Comment by ens-ma7** [comment]
Also i wanted to submit a job so that i can have a look at the parameters submitted in the database but i can't submit a job on the sandbox. @azangru few things to check if you have your sandbox setup properly:
1) check if you have the tools_hive plugin enable
2) If you do have the plugin enable, can you remove your MULTI.packed file and restart your sandbox.
3) Also can you please check beekeeper dev is running

**Comment by azangru** [comment]
@ens-ma7 

I have made sure tools work in the sandbox (turned out ensembl-hive code got switched to master with the bulk git-ensembl --checkout master available command, and had to be switched back to version 2.2). Thanks to @jyothishnt for help.

**Comment by ens-ma7** [comment]
I have just tried running a job for Data Slicer on your sandbox and it seems that the 1000Genome API is using the new FTP url and returning blank.

**Comment by azangru** [comment]
@ens-ma7 it turned out that the ftp server ftp://ftp.ebi.ac.uk/1000g/ftp was misconfigured, and Ensembl server could not access files on it. Web prod has fixed the ftp server; so at least the sandbox works now. Don't know how high of a load that server can take.

**Comment by ens-ma7** [comment]
Since this is a temporary fix for the DC migration, we need to make the PR against the release/99 branch and it will be reverted back in release/100.

**Comment by ens-ma7** [comment]
codes change are ok and manage to run a job successfully with the right ftp parameters in the tools db. 
Once you make this PR against release/99 branch only, should be good.

**Comment by azangru** [comment]
Changed the base branch to release/99 😃

**Pull request merged**
