### PR TITLE
Pig-strains gene-trees not shown on staging #5275 

### PR DESCRIPTION
**Pull request by msmanoj**
Fixed the issue with missing 'Strains' link on the nav bar for Pigs.

Related JIRA ticket:
https://www.ebi.ac.uk/panda/jira/browse/ENSWEB-5275

Views affected:
http://ves-hx2-76.ebi.ac.uk:42228/Sus_scrofa/Gene/Summary?g=ENSSSCG00000004244;r=1:42729112-42896283

### CODE REVIEW

**Comment by ens-ap5** [comment]
Manoj, could you add a few instructions about this to the corresponding release ticket, so it doesn't get missed again? 
https://www.ebi.ac.uk/panda/jira/browse/ENSWEBREL-989

**Comment by msmanoj** [comment]
Hi @ens-ap5, I have added some instructions to the ticket you have mentioned. Could you please check if it is sufficient?

**Comment by ens-ma7** [comment]
The code change looks good but you need to do your PR against postreleasefix/98 branch. The other thing once you merged the changes and updated test, dont forget we need to repacked the files in order to see the changes.

**Comment by ens-ap5** [comment]
Regarding the JIRA ticket, let's discuss it outside GitHub since it's not relevant to this PR.

**Pull request merged**
