### PR TITLE
[CAFE view] Use the precomputed JSON

### PR DESCRIPTION
**Pull request by muffato**
cf https://github.com/Ensembl/ensembl-webcode/pull/372

### CODE REVIEW

**Comment by ens-ma7** [comment]
Hi Matthieu
The sub get_details is going to overwrite the one from the main code (ensembl-webcode/modules/EnsEMBL/Web/Component/Gene/SpeciesTree.pm). Are you sure you want to do this? 
If so, i will suggest to move the sub get_details to main code and need to make sure it will work with the fallback view.

**Comment by muffato** [comment]
That's actually why I'm doing it this way: the precomputed JSON is only useful for the new view since the fallback view is Perl only. So I think it's fine to override get_details in public-plugins/widget. Both views have their own `get_details()` and `content()`

**Comment by ens-ma7** [comment]
Sorry Matthieu, doing it this way will make it use the get_detail inside the widget plugin, this is how the plugins work. Any function inside a plugin will overwrite the main one. 
The solution to this is to have a different get_detail function in the plugin (say get_json) and then call get-json instead of get_details inside the plugins component code.
Hope that makes sense, let me know if there is anything not clear.

**Comment by muffato** [comment]
Aaaah I understand: the widget modules are all in PERL5LIB of the server, regardless of the whether the client needs the fallback view or the JavaScript one. Got it
I will amend the commit and update the PR

**Comment by ens-ma7** [comment]
Thank you

**Comment by muffato** [comment]
Done. It still works on my sandbox

**Pull request merged**
