### PR TITLE
remove bad chimp example

### PR DESCRIPTION
**Pull request by sarahhunt**
@ens-st3 - if required

### CODE REVIEW

**Comment by ens-st3** [comment]
@msmanoj can you push out as a post release bugfix ?

**Comment by msmanoj** [comment]
@ens-st3 sure, i'll get it pushed ASAP after the release.

**Comment by msmanoj** [comment]
Hi @sarahhunt, could you check if this change looks good on live, please? Thanks

**Comment by sarahhunt** [comment]
That looks good - thanks @msmanoj !

**Pull request merged**
