### PR TITLE
Added doc for 3 new consequence terms

### PR DESCRIPTION
**Pull request by nakib103**
There are 3 new consequence terms introduced in the e106. We need to present them in the doc.

### CODE REVIEW

**Comment by nakib103** [comment]
@jamie-m-a , can you please check?

**Comment by jamie-m-a** [comment]
Looks good to me!

**Comment by jamie-m-a** [comment]
Thank @nakib103 All good for me.

**Comment by nakib103** [comment]
thanks @jamie-m-a, updated the image to original dimensions.

**Review by jgtate — APPROVED** [review]

**Pull request merged**
